name: "🪲 Bug Report"
description: Report an issue/bug with the application
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: What should have happened?
      placeholder: Describe the expected behaviour
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error
    validations:
      required: false

  - type: dropdown
    id: version
    attributes:
      label: MicMuter Version
      description: What version of MicMuter were you running? (Hover cursor over tray icon to see)
      options:
        - 2.0.0
        - 1.2.0
        - 1.1.0
        - 1.0.0
      default: 0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 11
        - Windows 10
        - MacOS
        - Linux
      default: 0
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS (Build) Version
      description: If linux, include distro and DE
    validations:
      required: true

  - type: dropdown
    id: installed-from
    attributes:
      label: "Installed from:"
      options:
        - GitHub
        - WinGet
        - Microsoft Store
        - Other (please specify in "Steps to reproduce")
    validations:
      required: false

  - id: additionalInfo
    type: textarea
    attributes:
      label: Additional Information
      description: Attatch logs, screenshots, other relevant files, etc.
      placeholder: |
        Running as admin
        .Net version
    validations:
      required: false
